import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Header from '@/modules/Header'
import Footer from '@/modules/Footer'
import Sidebar from '@/modules/Sidebar'
import {SidebarProvider} from '@/contexts/SidebarProvider'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SidebarProvider>
          <main className='flex flex-col min-h-screen'>
            <Header />
            <div className='flex-grow grid grid-cols-5 gap-4 pt-[60px]'>
              <Sidebar />
              <div className='lg:w-custom lg:ml-auto col-span-5 lg:col-span-6'>
                {children}
              </div>
            </div>
            <Footer />
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
